"""Add start and end for filter model

Revision ID: 003d54547492
Revises: 82bb618a44b5
Create Date: 2021-06-18 13:04:54.892296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003d54547492'
down_revision = '82bb618a44b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filters', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('filters', sa.Column('end_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filters', 'end_at')
    op.drop_column('filters', 'start_at')
    # ### end Alembic commands ###
