"""Drop table event_themes

Revision ID: 50eea56818d4
Revises: 18230484849c
Create Date: 2021-06-14 15:50:47.445436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50eea56818d4'
down_revision = '18230484849c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Player Dates')
    op.drop_table('event_themes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_themes',
    sa.Column('theme_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_themes_event_id_fkey'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name='event_themes_theme_id_fkey')
    )
    op.create_table('Player Dates',
    sa.Column('theme_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='Player Dates_event_id_fkey'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name='Player Dates_theme_id_fkey')
    )
    # ### end Alembic commands ###
