"""Change filters city_id nullable

Revision ID: 70534db9d192
Revises: 003d54547492
Create Date: 2021-06-18 21:29:21.506206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70534db9d192'
down_revision = '003d54547492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filters', 'city_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filters', 'city_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
